name: Zloof
favicon: null
layout_spectrum: 0.8851411377545446
typography_spectrum: 0.20225017401389778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8125
  lightness: 0.9575727703049779
  saturation: 0.1875
  rhythmicContrast: 0.48056140332482755
purpose: []
